# Generated by Django 4.2.17 on 2025-04-07 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
