# Generated by Django 4.2.17 on 2025-04-07 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_by',
            new_name='created_by_id',
        ),
    ]
