# Generated by Django 4.2.17 on 2025-04-07 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_created_by_product_created_by_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_by_id',
            new_name='user',
        ),
    ]
