# Generated by Django 4.2.17 on 2025-04-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_quantity_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='price_purchase',
        ),
        migrations.AddField(
            model_name='product',
            name='price_selling',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
