# Generated by Django 4.2.17 on 2025-04-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_rename_price_product_price_purchase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('seller', 'Seller'), ('customer', 'Customer')], default='buyer', max_length=10),
        ),
    ]
