# Generated by Django 4.2.17 on 2025-04-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_selling',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
