# Generated by Django 4.2.17 on 2025-04-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_customer_address_remove_customer_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='completed_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Thanh toán khi nhận hàng'), ('card', 'Thẻ ngân hàng')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('shipping', 'Đang giao'), ('delivered', 'Đã giao'), ('cancelled', 'Đã huỷ')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
