# Generated by Django 4.2.17 on 2025-04-13 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_rename_shipping_address_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_line',
        ),
        migrations.RemoveField(
            model_name='address',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='address',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='address',
            name='recipient_name',
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='Hà Nội', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='ward',
            field=models.CharField(default='', max_length=100),
        ),
    ]
