# Generated by Django 4.2.17 on 2025-04-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_address_address_line_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
    ]
